# -*- coding: utf-8 -*-
"""Proyek Kedua: Sistem Rekomendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138i1Nkwcs7YemZlF2e9T3cdxplkzFpGv

Sistem Rekomendasi Anime

# Data Understanding
"""

# Import library
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load data
!pip install kaggle

from google.colab import files
files.upload()

!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d CooperUnion/anime-recommendations-database
!unzip anime-recommendations-database.zip

"""## Variabel Anime

"""

# Membuat dataset bernama anime
anime = pd.read_csv('anime.csv')
anime.head()

"""- `anime_id`: Id unik untuk judul anime
- `name`: Nama anime
- `genre`: Genre anime
- `type`: Tipe seperti Movie, TV, OVA, dll
- `episodes`: Jumlah episode
- `rating`: rating untuk anime
- `members`: jumlah anggota komunitas anime tersebut

"""

anime.info()

anime.shape

"""Pada data `anime` terdapat 7 kolom dengan 12.294 baris data"""

# Melihat jumlah genre dan apa saja genrenya
print('Banyak genre anime: ', len(anime.genre.unique()))
print('genre: ', anime.genre.unique())

"""Jumlah genre pada data `anime` adalah 3265 data"""

# Cek missing value
anime.isnull().sum()

"""Pada data `anime` terdapat missing value pada beberapa fitur sebagai berikut:
- `genre`: 62 data
- `type`: 25 data
- `rating`: 230 data

missing value ini akan kita hapus nanti saattahap preparation

## Variabel Rating
"""

# Membuat dataset bernama ratings
ratings = pd.read_csv('rating.csv')
ratings.head()

"""- `user_id`: Id user.
- `anime_id`: id anime.
- `rating`: Rating dari user (jika bernilai -1 berarti user hanya menonton dan tidak memberi rating).

"""

ratings.info()

ratings.shape

"""Pada data `ratings` terdapat 3 kolom dengan 7.813.737 baris data"""

# Cek missing value
ratings.isnull().sum()

"""Tidak terdapat missing value pada data `ratings`"""

# cek jumlah data yang ratingnya -1
ratings[ratings.rating == -1].shape

"""Terdapat 1.476.496 data yang memiliki `rating` bernilai -1 atau bisa dibilang sebanyak 1.476.496 user hanya menonton tanpa memberikan rating terhadap anime tersebut

# Data Preparation

## Mengatasi Missing Value pada data `anime`
"""

# Menghapus baris dengan missing value pada kolom 'genre', 'type', dan 'rating'
anime.dropna(subset=['genre', 'type', 'rating'], inplace=True)

# Cek kembali missing value
anime.isnull().sum()

"""Missing value pada data `anime` berhasil dihapus

## Menghapus rating bernilai -1 pada data `ratings`
"""

# Menghapus baris dengan rating -1
ratings = ratings[ratings.rating != -1]

# Cek kembali data
ratings.head()
ratings.shape

"""`rating` bernilai -1 pada data `rating` berhasil dihapus dan sisa data sekarang adalah 6.337.241 baris data

## Menggabungkan data anime dan ratings
"""

# Menggabungkan data
df = pd.merge(anime, ratings, on='anime_id', how='inner')
df.head()

"""Penggabungan data berhasil
karena sebelumnya terdapat 2 fitur `rating` pada masing-masing data, ootomatis namanya berubah mennjadi:
- `rating_x`: rating keseluruhan anime
- `rating_y`: rating yang diberikan user
"""

df.shape

"""Jumlah data setelah di merge menjadi 9 kolom dengan total 6.337.146 baris data

# Mengatasi duplicate data fitur `name`
"""

# Cek jumlah duplicate data pada fitur 'name'
df.name.value_counts()

# Hapus duplicate data pada fitur 'name' lalu memasukkannya pada variabel baru bernama 'preparation'
preparation = df.drop_duplicates('name')
preparation

"""Setelah menghapus semua duplicate pada baris `name`, sisa data menjadi 9892 baris"""

# Cek kembali jumlah duplicate data pada fitur 'name'
preparation.name.value_counts()

"""Sudah tidak ada duplicate data pada variabel `preparation`

## Membuat dictionary pada fitur `anime_id`, `name`, dan `genre`
"""

# Melakukan konversi data series menjadi list
anime_id = preparation['anime_id'].tolist()
name = preparation['name'].tolist()
genre = preparation['genre'].tolist()

print(len(anime_id))
print(len(name))
print(len(genre))

# Membuat dictionary lalu memasukkannya pada variabel 'df_new"
df_new = pd.DataFrame({
    'anime_id': anime_id,
    'name': name,
    'genre': genre
})
df_new

"""Data `df_new` sudah siap masuk ke dalam permodelan

# Modelling

## Model Development dengan Content Based Filtering
"""

# Menampilkan 5 data random
df_new.sample(5)

# Inisialisasi TfidfVectorizer
tf = TfidfVectorizer()

# Melakukan perhitungan idf pada data genre
tf.fit(df_new['genre'])

# Mapping array dari fitur index integer ke fitur name
tf.get_feature_names_out()

# Melakukan fit lalu ditransformasikan ke bentuk matrix
tfidf_matrix = tf.fit_transform(df_new['genre'])

# Melihat ukuran matrix tfidf
tfidf_matrix.shape

"""Nilai 9882 merupaka ukuran data, sedangkan 47 adalah matriks ukuran genre"""

# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

# Membuat dataframe untuk melihat tf-idf matrix
# Kolom diisi dengan genre
# Baris diisi dengan nama anime

num_cols_to_sample = min(47, len(tf.get_feature_names_out()))  # Ensure sample size <= number of columns
num_rows_to_sample = min(10, tfidf_matrix.shape[0]) # Ensure sample size <= number of rows

pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tf.get_feature_names_out(),
    index=df_new.name
).sample(num_cols_to_sample, axis=1, replace=False).sample(num_rows_to_sample, axis=0, replace=False)

# Menghitung cosine similarity pada matrix tf-idf
cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

# Membuat dataframe dari variabel cosine_sim dengan baris dan kolom berupa nama anime
cosine_sim_df = pd.DataFrame(cosine_sim, index=df_new['name'], columns=df_new['name'])
print('Shape:', cosine_sim_df.shape)

# Melihat similarity matrix pada setiap nama anime
cosine_sim_df.sample(5, axis=1).sample(10, axis=0)

def anime_recommendations(nama_anime, similarity_data=cosine_sim_df, items=df_new[['name', 'genre']], k=5):
    index = similarity_data.loc[:,nama_anime].to_numpy().argpartition(
        range(-1, -k, -1))

    # Mengambil data dengan similarity terbesar dari index yang ada
    closest = similarity_data.columns[index[-1:-(k+2):-1]]

    # Drop nama_anime agar nama resto yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(nama_anime, errors='ignore')

    return pd.DataFrame(closest).merge(items).head(k)

# Menampilkan data pada anime `Detective Conan OVA 11: A Secret Order from London`

df_new[df_new.name.eq('Detective Conan OVA 11: A Secret Order from London')]

# Menampilkan 5 rekomendasi
anime_recommendations('Detective Conan OVA 11: A Secret Order from London')

"""Rekomendasi 5 anime baru yang sesuai dengan `Detective Conan OVA 11: A Secret Order from London` sudah muncul

# Evaluation
"""

# Evaluasi model
Tp = 5
Fp = 0

Precision = (Tp / (Tp + Fp))*100
print(Precision)

"""- Precision mengukur proporsi prediksi positif yang benar dibandingkan dengan semua prediksi positif.
- Tp = True positive (Jumlah prediksi positif yang benar)
- Fp = False positive (jumlah prediksi negatif yang benar)

Berdasarkan pada precision evaluasinya, didapatkan nilai 100% pada precisionnya. Ini menandakan prediksi benar semua
"""